plantnet_file_manager_homepage:
    pattern:  /file_manager/
    defaults: { _controller: PlantnetFileManagerBundle:Default:index }

plantnet_file_manager_upload:
    pattern:  /file_upload/
    defaults: { _controller: PlantnetFileManagerBundle:Default:upload }
    methods:    [POST]
