# src/Plantnet/FileManagerBundle/Resources/config/validation.yml
Plantnet\FileManagerBundle\Entity\ZipData:
    properties:
        zipFile:
            - NotBlank: ~
            - File:
                maxSize: 250M
                mimeTypes: [application/zip,application/x-zip]